export const RESQUEST_DANG_KY = "@DangKy/RESQUEST_DANG_KY";
export const RESQUEST_DANG_KY_SUCCESS = "@DangKy/RESQUEST_DANG_KY_SUCCESS";
export const RESQUEST_DANG_KY_FAIL = "@DangKy/RESQUEST_DANG_KY_FAIL";