export const REQUEST_API_NGUOI_DUNG = "@NguoiDung/REQUEST_API_NGUOI_DUNG";
export const REQUEST_DS_NGUOI_DUNG_SUCCESS = "@NguoiDung/REQUEST_DS_NGUOI_DUNG_SUCCESS";
export const REQUEST_DS_NGUOI_DUNG_FAIL = "@NguoiDung/REQUEST_DS_NGUOI_DUNG_FAIL";