export const REQUEST_CHI_TIET_PHIM = "@ChiTietPhim/REQUEST_CHI_TIET_PHIM";
export const REQUEST_CHI_TIET_PHIM_SUCCESS = "@ChiTietPhim/REQUEST_CHI_TIET_PHIM_SUCCESS";
export const REQUEST_CHI_TIET_PHIM_FAIL = "@ChiTietPhim/REQUEST_CHI_TIET_PHIM_FAIL";