export const REQUEST_LICH_CHIEU_PHIM = "@LichChieuPhim/REQUEST_LICH_CHIEU_PHIM";
export const REQUEST_LICH_CHIEU_PHIM_SUCCESS = "@LichChieuPhim/REQUEST_LICH_CHIEU_PHIM_SUCCESS";
export const REQUEST_LICH_CHIEU_PHIM_FAIL = "@LichChieuPhim/REQUEST_LICH_CHIEU_PHIM_FAIL";