export const REQUEST_DS_PHIM_DANG_CHIEU = "@PhimDangChieu/REQUEST_DS_PHIM_DANG_CHIEU";
export const REQUEST_DS_PHIM_DANG_CHIEU_SUCCESS = "@PhimDangChieu/REQUEST_DS_PHIM_DANG_CHIEU_SUCCESS";
export const REQUEST_DS_PHIM_DANG_CHIEU_FAIL = "@PhimDangChieu/REQUEST_DS_PHIM_DANG_CHIEU_FAIL";
