export const RESQUEST_DANG_NHAP = "@DangNhap/RESQUEST_DANG_NHAP";
export const RESQUEST_DANG_NHAP_SUCCESS = "@DangNhap/RESQUEST_DANG_NHAP_SUCCESS";
export const RESQUEST_DANG_NHAP_FAIL = "@DangNhap/RESQUEST_DANG_NHAP_FAIL";