export const REQUEST_LICH_CHIEU_PHIM = "@ShowtimeComp/REQUEST_LICH_CHIEU_PHIM";
export const REQUEST_LICH_CHIEU_PHIM_SUCCESS =
  "@ShowtimeComp/REQUEST_LICH_CHIEU_PHIM_SUCCESS";
export const REQUEST_LICH_CHIEU_PHIM_FAIL =
  "@ShowtimeComp/REQUEST_LICH_CHIEU_PHIM_FAIL";
export const SELECT_NGAY_CHIEU_PHIM = "ShowtimeComp/SELECT_NGAY_CHIEU_PHIM";
export const SELECT_HE_THONG_RAP = "@ShowtimeCompo/SELECT_HE_THONG_RAP";
